### ISSUE TITLE
Submitpost is not working

### ISSUE THREAD

**Issue by Paramchoudhary** [Ahmedsaed/MLH-Hacker-Protal#3]
can u give me a reason why it's not working ??? plz reply Ahmed

**Comment by ahmedsaed** [comment]
Hi @Paramchoudhary,

Thanks for the report.
I just tested the webapp and there is no issues with submitting posts.

https://user-images.githubusercontent.com/37080003/162985106-bf01b08b-8842-4cea-b95b-8f8d55e04492.mp4

**Can you clarify what's exactly not working, maybe send a screenshot of the error?**

By the way, This project is still under development and there may be some bugs.
I started this project as a submission for some of "MLH Global Hack Week" Hackathon challenges. I am probably going to rebrand it and keep developing

**Comment by Paramchoudhary** [comment]
Uploading Ahmed.mov

**Comment by Paramchoudhary** [comment]
https://user-images.githubusercontent.com/69947192/163099442-0f1ac7c9-1429-4d15-8909-07a67ea9cda7.mp4

this is not working on my side. can u please help me bro.
this is very important for me.

**Comment by ahmedsaed** [comment]
Hi @Paramchoudhary,

I can't help you without knowing the error

Can you please preform the following steps:
- `right click` then `inspector`
- open the console tab 
- create a post (please click on the submit button once)
- then send me a screenshot of the output in the console

Also, please confirm that your deso account has enough deso coins to create a post

**Comment by Paramchoudhary** [comment]
Sure 🙏💛

**Comment by Paramchoudhary** [comment]
Thanks man now its working fine
